### ISSUE TITLE
Returns lines that don't have a newline

### ISSUE THREAD

**Issue by tcoopman** [alexmiddeleer/node-file-tail#4]
I was testing your module but noticed a bug. The module returns all data and doesn't check if there is a newline before returning the line.

So if `abc` is stored as last line, it will return `abc`. If that line later changes to `abcdef\n` it will return `def`.
I would expect the module to wait for the newline and then return `abcdef`

**Comment by alexmiddeleer** [comment]
I will check it out tonight if I have time; I don't actually remember if this was intended behavior or a mistake.  I think it might be the intended behavior since if I recall it goes off of the number of new bytes.
