### ISSUE TITLE
Stop node-file-tail watching a file

### ISSUE THREAD

**Issue by bsocius** [alexmiddeleer/node-file-tail#5]
Hi everybody,

I am a bit clueless (new to javascript), but how do i stop the watching of a file?

**Comment by Jacob-Friesen** [comment]
You just need to get return of startTailing() and call stop() on it. For example, to stop watching a file after 2 seconds:

    var tailer = fileTail.startTailing('test.txt');
    tailer.on('line', console.log);

    setTimeout(function() {
      tailer.stop();
    }, 2000)

This works because this library returns a [node-file-size-watcher](https://github.com/alexmiddeleer/node-file-size-watcher) on startTailing which has a stop() method.
